// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Spotify
{
    internal sealed partial class Vsix
    {
        public const string Id = "Spotify.03f3b026-0e2f-4ad4-b718-87710cd542e5";
        public const string Name = "Spotify";
        public const string Description = @"Spotify web extension for Visual Studio can enhance the developer experience by allowing users to control music playback or browse Spotify content directly within the IDE.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu Kumar Sharma HKS";
        public const string Tags = "";
    }
}
